spring:
  application:
    name: gateway-demo
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://127.0.0.1:8081/hello
          predicates:
            - Path=/hello

  sleuth:
    baggage:
      remote-fields: session-id
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{session-id:-}]"

